/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 17-дек-2024 18:04:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS t2t CASCADE
;

/* Create Tables */

CREATE TABLE t2t
(
	id bigint NOT NULL,
	message varchar(256) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE t2t ADD CONSTRAINT "PK_t2t"
	PRIMARY KEY (id)
;
