/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 17-дек-2024 18:13:21 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

--DROP TABLE IF EXISTS thread_state CASCADE;--

/* Create Tables */

CREATE TABLE thread_state
(
	id varchar(50) NOT NULL,
	is_running boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE thread_state ADD CONSTRAINT "PK_thread_state"
	PRIMARY KEY (id)
;
